services:
  traveling-app:
    container_name: traveling-app
    image: traveling-app-alpine
    build:
      context: ..
      dockerfile: src/TravelingApp.API/Dockerfile
    depends_on:
      postgres-traveling-app:
        condition: service_healthy
      redis-traveling-app:
        condition: service_started
    networks:
      - traveling-network

  postgres-traveling-app:
    container_name: postgres-traveling-app
    image: postgres:18.3-alpine
    networks:
      - traveling-network

  redis-traveling-app:
    container_name: redis-traveling-app
    image: redis:8.6.2-alpine
    networks:
      - traveling-network

networks:
  traveling-network:
    driver: bridge
