services:
  travelingapp:
    build:
      context: ..
      dockerfile: src/TravelingApp.Ui/Dockerfile
    depends_on:
      - postgres
      - redis
    networks:
      - travel-network

  postgres:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - travel-network

  redis:
    image: redis:7.0.15
    networks:
      - travel-network

volumes:
  postgres_data:

networks:
  travel-network:
